# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Artist.create(artist_name: 'カミラ・カベロ', artist_profile: 'カーラ・カミラ・カベロ・エストラバオはキューバ・ハバナ生まれ、アメリカ合衆国フロリダ州マイアミ出身のシンガーソングライター。2012年からフィフス・ハーモニーのメンバーとして活動していたが、2016年に脱退。身長157cm。')
Artist.create(artist_name: 'ベッキー・G', artist_profile: 'ベッキー・Gはメキシコ系アメリカ人。ナレーション業のアルバイトをしながら2009年からG.L.A.Mというガールズグループとして活動。2011年に自身の歌、ダンスをYouTubeに投稿したところ、一気に注目される。2014年4月に発表したシングル曲「Shower」が自身の初めてのビルボードチャートインにして16位ランクイン。')
Artist.create(artist_name: 'カロル・G', artist_profile: 'カロル・Gはコロンビア・メデジン出身のレゲトンシンガー。ソーシャルメディアへの自身の歌の投稿が注目を集め、デビュー。トップレゲトンシンガーには男性が多い中、引けを全く取らないパワフルさで人気が高い。')
Artist.create(artist_name: 'ダディ・ヤンキー', artist_profile: '言わずと知れたレゲトンの王者、ダディ・ヤンキー。日本のディスコでも大ヒットをした「Gasolina」を始め、彼の歌う曲は常に大ヒット。楽しい毎日を過ごすのに絶対欠かせないシンガー。ここ１０年ほどはルックスが全く変化していないこともよくネタにされる。')
Artist.create(artist_name: 'バッド・バニー', artist_profile: 'プエルトリコ出身の、今一番アツいトラップシンガー。スーパーマーケットでのアルバイト中に自作の歌を歌っており、それが有名になってデビュー。個性的なファッションにも注目が高く、社会問題や「個性」をテーマにしたアツい歌が多いのも特徴。')
Artist.create(artist_name: 'ウィシン＆ヤンデル', artist_profile: 'レゲトンの歴史に欠かせないレジェンドの一角。現在はそれぞれ個人での音楽活躍を行いながらも２人でのライブや新曲も出し続けており、仲の良さは明らか。時代の変化についてくるおじさん達は全く年齢を感じさせず常に時代の最先端をゆく。')
Artist.create(artist_name: 'J・バルヴィン', artist_profile: 'モダン・レゲトンを先頭で引っ張る、コロンビア・メデジン出身のJ・バルヴィン。２０１８年のサマーソニックで初日本ライブを行った。アメリカのビルボードのトップも何度も奪っている。大のスニーカーズき。頻繁に色が変わるヘアスタイルに注目。')
Artist.create(artist_name: 'CNCO', artist_profile: '南米のOne Direction的な存在。拠点はアメリカ。男性グループの中ではメンバーの脱退などなしにとても長く続いている。英語とスペイン語両方を使い、アメリカと中南米をつなぐ存在。ティーン向けの印象が強いが、意外と素敵なバラードも多い。２０１８年に日本来日、ヴィーナスフォートでライブを行った。')
Artist.create(artist_name: 'マルマ', artist_profile: '２０代で今一番セクシーな歌手といったらこの人。コロンビア・メデジン出身のマルマはとにかく顔がイケメンでインスタグラムのフォロワー数がラテン系シンガーで一位となっている。曲もセクシーなものが多いが、ライブに行くとちょっとがっかりする。２０１９年に入りロン毛をバッサリ切ったところ、昔よりもイケメンに戻れず残念。そんなところもご愛嬌。')
Artist.create(artist_name: 'マヌエル・トゥリソ', artist_profile: 'コロンビア・モンテリア出身の１９歳。ハード系に多い、スーパーアルトな声で歌われるスーパー優しい楽曲が人々の心を掴んでやまない、次世代を作る大型ルーキー。所属レーベルも特殊で、少数精鋭なマネージャーに見込まれデビュー。カッコつけることがまだできず、ニコニコと笑顔の写真が多いのも人気の秘訣。')
Cd.create(cd_title: '', stock: 5, cd_profile: '.', price: 1000, artist_id: 2)
Cd.create(cd_title: 'ハバナ', stock: 5, cd_profile: '全世界で大ヒットしたカミラ・カベロの「ハバナ」。２２歳が歌っているとは全く信じられないムーディでセクシーな曲で、しっぽりとしたバーなどが似合う。祖国キューバの首都ハバナにて、悪い男とわかっていながらひっかかってしまうという若い女の子の心を歌う。', price: 1000, artist_id: 1)
Cd.create(cd_title: 'マヨーレス', stock: 5, cd_profile: '「スーツの似合う、年上でインテリな男の人が好きなの」という内容のセクシーな一曲。しかも、当時まだ２０歳だったベッキー・Gが、こちらもまだ２１歳と年上好きの女の子からしたら「恋愛対象外」なバッド・バニーが歌うところがいい。ベッキー・Gが可愛いことはもちろん、バッド・バニーの歌う若い男の子が女の子を落とそうと頑張るところもすごく良い。', price: 1000, artist_id: 2)
Cd.create(cd_title: 'ミ・カマ', stock: 5, cd_profile: '曲の内容は聞いてはダメ。メロディを楽しむ、カロル・Gの大ヒットパーティソング。男性シンガーに絶対負けないパワフルさを持つカロル・Gが歌うからこそ、「私のベッドはよく軋むの」なんていうだいぶハードな歌詞もサラッと爽やかに、ノリよく聞けてしまいます。', price: 1000, artist_id: 3)
Cd.create(cd_title: 'Dura', stock: 5, cd_profile: 'クラブやダンスにぴったりで、全世界で大ヒットしたダディ・ヤンキーのDura。ソーシャルメディアで世界中に広まった一曲。ビビッドカラーをうまく使った、明るくて楽しいPVも必見。撮影場所はロサンゼルスのビーチ。', price: 1000, artist_id: 4)
Cd.create(cd_title: 'Si Tu Novio Te Deja Sola', stock: 5, cd_profile: 'まさにジャケ買いにオススメな一枚。イントロ部分から終始とってもイージーでリラクシングな曲調もジャケットとぴったりマッチ。ちなみにサビ部分は「もし彼氏に一人にされたら俺に電話して。１、2時間で迎えに行くから」と歌っています。', price: 1000, artist_id: 5)
Cd.create(cd_title: 'ロス・カンペオネス', stock: 5, cd_profile: 'ハードな曲でちょっと盛り上がりたい時にはウィシン＆ヤンデルで決まり。２０１８年発売のこのアルバムでは、時代の変化にしっかり追いつくどころか常に先を走るこの二人の姿にあっぱれ。とてもファッショナブルで熱くて、でもたまにトラディショナルな雰囲気を感じさせてくれる、ウィシン＆ヤンデルの軌跡を感じる一枚。', price: 1000, artist_id: 6)
Cd.create(cd_title: 'ミ・ヘンテ', stock: 5, cd_profile: 'もはや説明は不要、世界中に現代のレゲトンを知らしめ、その価値を確固たるものにし、世界中のディスコ・クラブ・パーティで聞かれたこの曲ミ・ヘンテ。問答不要でおうちに一枚どうぞ。', price: 1000, artist_id: 7)
Cd.create(cd_title: 'パラ・エナモラールテ', stock: 5, cd_profile: '「君が恋に落ちるために」というタイトルのCNDOのアルバム。デビュー時はまさにOne Directionのラテン版、と言ったティーン感強めな彼らでしたが、こんなにしっぽりと優しく甘い曲も歌える男になりました。オトナな女性にぜひ聞いてほしいアルバムです。', price: 1000, artist_id: 8)
Cd.create(cd_title: 'HP', stock: 5, cd_profile: '２０１９年マルマの新曲は失恋直後の女の子の歌。「今は彼氏はいらない」という女の子を煽る、色男マルマらしいシングルです。', price: 1000, artist_id: 9)
Cd.create(cd_title: 'ソラ', stock: 5, cd_profile: '優しいバラードがとにかく上手なマヌエル・トゥリソから、少しアップテンポな一曲が登場。彼らしい優しい歌詞はそのままに、ディスコでも乗って踊れそうなメロディです。上品で穏やかな彼の印象は保たれているのでご安心を。', price: 1000, artist_id: 10)
Cd.create(cd_title: 'チャンベア', stock: 5, cd_profile: 'バッド・バニーの看板ソング。とにかく勢いが欲しい時にどうぞ。これなしにパーティは始まれない。盛り上がりたい時にとにかく必須な１枚。お部屋に置いておくだけでも気分は常にマックスまで上がること間違いなし。', price: 1000, artist_id: 5)
Cd.create(cd_title: ' X100PRE', stock: 5, cd_profile: 'これは芸術作品、なバッド・バニーの最新アルバム。アメリカ最大の音楽祭Coachella2019での出演を始め、日に日に株を上げている彼。まだ２０代で感性も豊かな彼は大きな経験をたくさん積み重ね、それが音楽に反映されているのが明らかにわかり、ウォッチが楽しい歌手。２０１９年、今の彼の姿をこのアルバムで見て。', price: 1000, artist_id: 5)
Cd.create(cd_title: 'シン・パジャマ', stock: 5, cd_profile: 'ベッキー・Gにしか歌えない、可愛いくて少し小悪魔な一曲。ナッティ・ナターシャとのフューチャリング。衣装がとても可愛いのでPVも必見。２０１８年のガールズ・パワーに必須の一曲だった作品。', price: 1000, artist_id: 2)
Cd.create(cd_title: 'ミア', stock: 5, cd_profile: 'バッド・バニーとドレークのフューチャリング。２０１８年の１曲として様々な賞を受賞したので、説明はもはや不要。ドレークがスペイン語で歌っているところもアツい。', price: 1000, artist_id: 5)
Cd.create(cd_title: 'I Like It', stock: 5, cd_profile: 'You Tubeのコマーシャルでみんなサビだけは聞いていたであろうこの曲。カルディ・Bの両脇で歌うのは今を代表するJ・バルヴィンと、現役として前衛を走り続けるレジェンドニッキー・ジャム。脇役にするには大物すぎる２人を携えたカルディ・Bの人気がうなぎのぼりなのも納得。', price: 1000, artist_id: 5)
Category.create(category_name: 'J-Pop')
Category.create(category_name: 'ロック')
Category.create(category_name: 'ラップ')
Category.create(category_name: 'ソウル')
Category.create(category_name: 'カントリー')
Category.create(category_name: 'ジャズ')
Category.create(category_name: 'トラップ')
Label.create(label_name: 'ソニーミュージック')
Label.create(label_name: 'ユニバーサルミュージック')
Label.create(label_name: 'ワーナーミュージック')
